# Ansible role to execute a script
---
- name: Shell scripts section
  set_fact:
    section: "{{ hostvars['localhost'].profile_json['Shell'] }}"

- name: run command in shell
    shell: bash -ilc "{{ item.Script }}"
  with_items: "{{ section }}"
  become: "{{ item.Become }}"
  become_user: "{{ item.Become_User }}"
  become_method: "{{ item.Become_Method }}"

