---
# Ansble role to sync folders w/ rsync
- name: git section
  set_fact:
    section: "{{ hostvars['localhost'].profile_json['Sync'] }}"
    ansible_user: "{{ hostvars['localhost'].ansible_user }}"

- name: displaying directories to sync
  debug:
    msg: "{{ item }}"
  with_items: "{{ section }}"

- name: Transfer file from ServerA to ServerB
  synchronize:
    ssh_args: "-l {{ ansible_user }}"
    rsync_path: "/usr/bin/rsync"
    src: "{{ item.Source }}"
    dest: "{{ item.Dest }}"
    dest_port: 2222
  delegate_to: localhost
  run_once: true
  with_items: "{{ section }}"
