Apt_Pass_1:
  - Name: software-properties-common
  - Name: ca-certificates
  - Name: gnupg
  - Name: apt-transport-https
  - Name: sudo
  - Name: unzip
  - Name: git
  - Name: vim
  - Name: lsb-release
  - Name: python3-distutils
  - Name: python3-pip
  - Name: kubectl
  - Name: ansible
  - Name: build-essential
  - Name: checkinstall
  - Name: zlib1g-dev
  - Name: curl
  - Name: containerd
  - Name: runc
  - Name: docker.io
  - Name: openssl
  - Name: wget
  - Name: sysstat
  - Name: sl
  - Name: silversearcher-ag
  - Name: tree
  - Name: colordiff
  - Name: figlet
  - Name: cowsay
  - Name: terminator
  - Name: vlc
  - Name: libpam-yubico
  - Name: finger
  - Name: ssh
  - Name: nextcloud-desktop
  - Name: screen
  - Name: youtube-dl
  - Name: pandoc
  - Name: lynx
  - Name: gnome-software-plugin-flatpak
  - Name: snapd
Details:
  About: "dependancies + user"
  Name: Base
  Size:
  Comment: ""
